### ISSUE TITLE
ClientError: error deserializing plain value: data did not match any variant of untagged enum PlainValue

### ISSUE THREAD

**Issue by antontranelis** [p2panda/mushroom-app-tutorial#2]
I'm having an error when running `npm run schema`

```
> mushroom-app-tutorial@1.0.0 schema
> ts-node --esm --transpileOnly ./register-schema.ts

Create and deploy schemas for the mushroom tutorial app
Created schema field 0020a2f2bf06cf2e751ccf00b5723f5957831ff30ec59d3716490e46b3847b1582e3
Created schema field 00205fa94a2204630b1a71a40eb0d3dac03115a3961135a8136b37b45afcf24c2a9d
Created schema field 002087a31d8595d48b9c723f8affa45f7af7e82cc0be856c31d30fc5761f639f688c
Created schema field 00208c2d8ebe8b95fd4c4b02bd8595ed569e6ec5de1b816b70dbf809e08ddbe0713a
/home/heinz/workspace/p2panda/mushroom-app-tutorial/node_modules/graphql-request/dist/index.js:63
            op = body.call(thisArg, _);
                      ^
ClientError: error deserializing plain value: data did not match any variant of untagged enum PlainValue: {"response":{"data":null,"errors":[{"message":"error deserializing plain value: data did not match any variant of untagged enum PlainValue","locations":[{"line":3,"column":7}]}],"status":200,"headers":{}},"request":{"query":"\n    mutation Publish($entry: String!, $operation: String!) {\n      publish(entry: $entry, operation: $operation) {\n        logId\n        seqNum\n        backlink\n        skiplink\n      }\n    }\n  ","variables":{"entry":"00479fa93b147fbd88ff80412288727c1952943d0ace709a644525a585454e81d80401f901810020bbafb6a14f7bad4b91325d95035eac8b1157b2baf56a7238c1bf26ad513758a2b3c801c0d34517fd141e2ab7da8c98b375474168a9952c8bb91935e93ec35960047d2ad4823ff5f54ab53e190233046d3c79fd8f688ea3cac6d3d2a75ac0ae05","operation":"84010074736368656d615f646566696e6974696f6e5f7631a36b6465736372697074696f6e7828496e666f726d6174696f6e7320616e642064657461696c732061626f7574206d757368726f6f6d73666669656c6473848178443030323061326632626630366366326537353163636630306235373233663539353738333166663330656335396433373136343930653436623338343762313538326533817844303032303566613934613232303436333062316137316134306562306433646163303331313561333936313133356138313336623337623435616663663234633261396481784430303230383761333164383539356434386239633732336638616666613435663761663765383263633062653835366333316433306663353736316636333966363838638178443030323038633264386562653862393566643463346230326264383539356564353639653665633564653162383136623730646266383039653038646462653037313361646e616d65686d757368726f6f6d"}}}
    at /home/heinz/workspace/p2panda/mushroom-app-tutorial/node_modules/graphql-request/src/index.ts:497:11
    at step (/home/heinz/workspace/p2panda/mushroom-app-tutorial/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/home/heinz/workspace/p2panda/mushroom-app-tutorial/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/home/heinz/workspace/p2panda/mushroom-app-tutorial/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    data: null,
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '\n' +
      '    mutation Publish($entry: String!, $operation: String!) {\n' +
      '      publish(entry: $entry, operation: $operation) {\n' +
      '        logId\n' +
      '        seqNum\n' +
      '        backlink\n' +
      '        skiplink\n' +
      '      }\n' +
      '    }\n' +
      '  ',
    variables: {
      entry: '00479fa93b147fbd88ff80412288727c1952943d0ace709a644525a585454e81d80401f901810020bbafb6a14f7bad4b91325d95035eac8b1157b2baf56a7238c1bf26ad513758a2b3c801c0d34517fd141e2ab7da8c98b375474168a9952c8bb91935e93ec35960047d2ad4823ff5f54ab53e190233046d3c79fd8f688ea3cac6d3d2a75ac0ae05',
      operation: '84010074736368656d615f646566696e6974696f6e5f7631a36b6465736372697074696f6e7828496e666f726d6174696f6e7320616e642064657461696c732061626f7574206d757368726f6f6d73666669656c6473848178443030323061326632626630366366326537353163636630306235373233663539353738333166663330656335396433373136343930653436623338343762313538326533817844303032303566613934613232303436333062316137316134306562306433646163303331313561333936313133356138313336623337623435616663663234633261396481784430303230383761333164383539356434386239633732336638616666613435663761663765383263633062653835366333316433306663353736316636333966363838638178443030323038633264386562653862393566643463346230326264383539356564353639653665633564653162383136623730646266383039653038646462653037313361646e616d65686d757368726f6f6d'
    }
  }
}
```

Rust is version 1.75.0

**Comment by adzialocha** [comment]
Hi @antontranelis!

Unfortunately the tutorials are all outdated and we haven't managed to update this example application to the latest version (this is where this error comes from). Sorry for that! We will look into updating our website & tutorials next.

You can check out @sandreae's https://github.com/sandreae/dont-hug-me-im-gardening for a working JavaScript application in the meantime. Its nicely done and might serve as our next "tutorial app"

**Comment by sandreae** [comment]
Bumping `p2panda-js` to the latest version (`v0.8.1`) fixed this for me: https://github.com/p2panda/mushroom-app-tutorial/commit/7703d80c025780d7494ccb8a81fb6735bb97045a

Let us know if you have any other issues @antontranelis
